### PR TITLE
Submission Group 139: 2212046_2211740_2310717_2320010_2213144

### PR DESCRIPTION
**Pull request by minh-le1710**
**1. A brief description of your policy**

_**Best Fit Decreasing**_
Sort the list of products in descending order based on their area (width × height). Iterate through the sorted list and place each product in the position within the current stock that leaves the least remaining space (best fit). Products may be rotated to optimize space utilization. After placing a product, update the available space in the stock to reflect the new placement, ensuring no overlap occurs.

**_Random_**
Randomly choose a product from the list of available products that still need to be placed. Select a random position within the current stock to attempt placing the chosen product. If the product does not fit at the selected position, retry with a different position or select another product. Attempt to place the product at the chosen position, considering possible rotations. If placement is successful, update the stock layout accordingly; otherwise, continue the process until all products are placed or no suitable positions remain.

**2. Result**
| Policy  | Avg Filled Ratio | Avg Trim Lost | 
| ------------- | ------------- | ------------- |
| Best Fit Decreasing  | 0.19  | 0.25 |
| Random  | 0.45  | 0.65 |

**Explaination:**

_**Best Fit Decreasing (BFD) Algorithm:**_ Achieves a low trim_lost ratio while maintaining excellent processing time. It is highly efficient and competitive, making it suitable for models with large quantities.

_**Random Algorithm:**_ Results in a high trim_lost ratio but compensates with very short processing time. Its performance is subpar, making it only suitable for models with small quantities.

**3. Contributions**

| Team Member  | ID |  Contribution
| ------------- | ------------- | ------------- |
| Lê Nhật Minh | 2212046 | Algorithm implementation
| Lưu Chấn Kiến | 2211740 | Report
| Võ Thanh Đạt | 2310717 | Find case study
| Đỗ Quý | 2320010 | Find algorithm
| Nguyễn Việt Thành | 2213144 | Report

### CODE REVIEW

**Comment by minh-le1710** [comment]
**1. A brief description of your policy**


_**Best Fit Decreasing**_
Sort the list of products in descending order based on their area (width × height). Iterate through the sorted list and place each product in the position within the current stock that leaves the least remaining space (best fit). Products may be rotated to optimize space utilization. After placing a product, update the available space in the stock to reflect the new placement, ensuring no overlap occurs.

**_Random_**
Randomly choose a product from the list of available products that still need to be placed. Select a random position within the current stock to attempt placing the chosen product. If the product does not fit at the selected position, retry with a different position or select another product. Attempt to place the product at the chosen position, considering possible rotations. If placement is successful, update the stock layout accordingly; otherwise, continue the process until all products are placed or no suitable positions remain.

**2. Result**
| Policy  | Avg Filled Ratio | Avg Trim Lost | 
| ------------- | ------------- | ------------- |
| Best Fit Decreasing  | 0.19  | 0.25 |
| Random  | 0.45  | 0.65 |

**Explaination:**

_**Best Fit Decreasing (BFD) Algorithm:**_ Achieves a low trim_lost ratio while maintaining excellent processing time. It is highly efficient and competitive, making it suitable for models with large quantities.

_**Random Algorithm:**_ Results in a high trim_lost ratio but compensates with very short processing time. Its performance is subpar, making it only suitable for models with small quantities.

**3. Contributions**

| Team Member  | ID |  Contribution
| ------------- | ------------- | ------------- |
| Lê Nhật Minh | 2212046 | Algorithm implementation
| Lưu Chấn Kiến | 2211740 | Report
| Võ Thanh Đạt | 2310717 | Find case study
| Đỗ Quý | 2320010 | Find algorithm
| Nguyễn Việt Thành | 2213144 | Report

**Comment by martinakaduc** [comment]
Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

**Comment by martinakaduc** [comment]
Last chance to revise the PR until the end of Dec 17.

**Comment by martinakaduc** [comment]
Close PR as it does not comply with submission instructions.

**Comment by minh-le1710** [comment]
I sincerely apologize, Mr. [@martinakaduc](https://github.com/martinakaduc), for not regularly checking the Pull Request conversations.

I have rearranged the location of the file requirements.txt to ensure it complies.

Over the past week, I was solely focused on final exams and did not pay attention to this issue. Today, when I checked, it was already past the deadline. Additionally, all the members of my group are studying Computer Engineering (CE) and do not have prior experience using GitHub, which led to this situation. Could you please extend the deadline so that my group can submit the Pull Request? My group fully accepts the possibility of being penalized for the late submission as long as we do not receive a score of zero for this part.

**Pull request closed without merging**
