### PR TITLE
Revised submission Group 56: 2353086_2353007_2353988

### PR DESCRIPTION
**Pull request by Funacius**
# Report: Smallest/Largest Stock Policy
Team member:
Bùi Quốc Thái-2353086 (me)
Nguyễn Vinh Anh Quân-2353007 (Leader)
Hồ Lê Minh Quân-2352988
## Summary

The `Policy2353086_2353007_2353988` class implements two strategies for placing products into stocks:

1. **Smallest Stock Policy**:
   - Selects the smallest stock (by area) that can accommodate the product.
   - Aims to minimize the use of larger storage spaces for smaller products, preserving larger stocks for larger items.

2. **Largest Stock Policy**:
   - Selects the largest stock (by area) that can accommodate the product.
   - Aims to reduce complexity by prioritizing spacious stocks, potentially simplifying placement for future items.

Both policies ensure that products are placed efficiently, with fallback handling for cases where no suitable stock is available.

---

### Smallest Stock Policy
1. **Input Observation**:
   - Receive a list of products and available stocks with their dimensions.

2. **Sort Stocks**:
   - Sort stocks by area (smallest to largest).

3. **Evaluate Stocks**:
   - For each product, iterate through the sorted stocks to find the smallest stock that can accommodate the product's dimensions.

4. **Fit Assessment**:
   - Check possible positions within the stock for product placement.
   - Evaluate fit difference (stock area minus product area) to find the best placement.

5. **Place Product**:
   - If a valid position is found, return the stock index, product size, and position.
   - If no placement is possible, return a default action indicating failure.

### Largest Stock Policy
1. **Input Observation**:
   - Receive a list of products and available stocks with their dimensions.

2. **Sort Stocks**:
   - Sort stocks by area (largest to smallest).

3. **Evaluate Stocks**:
   - For each product, iterate through the sorted stocks to find the largest stock that can accommodate the product's dimensions.

4. **Fit Assessment**:
   - Check possible positions within the stock for product placement.
   - Evaluate wasted space (stock area minus product area) to minimize inefficiency.

5. **Place Product**:
   - If a valid position is found, return the stock index, product size, and position.
   - If no placement is possible, return a default action indicating failure.

---

### Smallest Stock Policy
**Advantages**:
- **Efficient Space Usage**:
  - Preserves larger stocks for bigger products, optimizing overall stock utilization.
- **Orderly Allocation**:
  - Encourages systematic usage of storage.

**Disadvantages**:
- **Complex Placement**:
  - Smaller stocks may require more computation to find valid positions.
- **Less Flexibility**:
  - Larger products may struggle to find placement if smaller stocks are over-utilized.

### Largest Stock Policy
**Advantages**:
- **Ease of Placement**:
  - Larger stocks provide more room, simplifying product placement.
- **Reduced Computation**:
  - Fewer checks required to find valid positions within spacious stocks.

**Disadvantages**:
- **Inefficient Space Usage**:
  - May leave smaller stocks underutilized, wasting valuable storage space.
- **Potential Bottlenecks**:
  - Over-reliance on larger stocks might limit options for future placements.

---

## Conclusion

Both the smallest and largest stock policies have unique strengths and weaknesses. The choice between them depends on the specific priorities of the storage system:

- Use **Smallest Stock Policy** for systems focused on optimizing space utilization.
- Use **Largest Stock Policy** for systems prioritizing simplicity and flexibility.

Future improvements could include:
- Combining strategies dynamically based on real-time conditions.
- Incorporating additional factors such as product weight, fragility, or retrieval frequency into the decision-making process.

### CODE REVIEW

**Comment by martinakaduc** [comment]
Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

**Comment by martinakaduc** [comment]
Last chance to revise the PR until the end of Dec 17.

**Comment by Funacius** [comment]
> Last chance to revise the PR until the end of Dec 17.
But what do i need to change in my PR

**Comment by Funacius** [comment]
> Merge lại bài đi ông

merge sao á ông

**Pull request merged**
