### PR TITLE
Submission 2313622_2312097_2310543_2312420_2311100 (Group 18)

### PR DESCRIPTION
**Pull request by phamtranminhtri**
## Group 18 code submission
Members list:
| Name               | Student ID | Class |
|--------------------|------------|-------|
| Phạm Trần Minh Trí | 2313622    | TN01  |
| Nguyễn Thiện Minh  | 2312097    | TN01  |
| Hồ Anh Dũng        | 2310543    | TN01  |
| Huỳnh Đức Nhân     | 2312420    | TN01  |
| Nguyễn Thái Học    | 2311100    | TN01  |

### Brief description

Our implementation include two main policy:

1. **Reinforcement Learning policy - Proximal Policy Optimazation** (`policy_id=1`): This policy uses PPO algorithm to train the agent. The trained parameters of the network is stored in `ppo_actor.pth` and that file is needed to run this policy (`ppo_critic.py` is only used for storing the critic network's parameters during the training process and is not required to run while testing). You need to run `pip install -r requirements.txt` to install the necessary libraries. The instruction to train the PPO network using `ppo_optimized.py` can be found in `README.md`.

2. **Hybrid policy - First Fit heuristic combined with RL** (`policy_id=2`): This is a reinforcement learning policy designed to optimize the cutting stock problem by improving upon a heuristic approach. The policy does not require prior training. During testing, it trains on a single specific episode provided by the user and then proceeds to testing. 

There is also an additional third policy:

3. **First Fit heuristic** (`policy_id=3`): This is the plain heuristic that is used for the second policy above.

### Summarized results

Average result over 100 episodes test (render disabled):

|                     | Average time per ep (second) | Average filled ratio per ep | Average trim loss per ep |
|---------------------|------------------------------|-----------------------------|--------------------------|
| RL-PPO policy       | 9.740                        | 0.2725                      | 0.4348                   |
| Hybrid heuristic-RL | 12.519                       | 0.1489                      | 0.0851                   |
| Plain heuristic     | 0.116                        | 0.1724                      | 0.1057                   |

### CODE REVIEW

**Comment by martinakaduc** [comment]
Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

**Comment by phamtranminhtri** [comment]
I have restore the s2210xxx folder and policy2210xxx.py. Please review my submission. Thank you!

**Comment by martinakaduc** [comment]
Last chance to revise the PR until the end of Dec 17.

**Comment by phamtranminhtri** [comment]
Dear teacher, we tried to resolve the conflict but it still had error, so please allow us to create a new submission instead. Thank you.

**Pull request closed without merging**
