### PR TITLE
Submission (Group 57): 2352113_2352103_2352740_2352570_2352442

### PR DESCRIPTION
**Pull request by BaoT08**
**Policy**
The Cutting Stock Problem focuses on cutting large stock materials into smaller pieces of specified lengths while minimizing waste. In this 2D Cutting Stock Problem, a distinctive feature is that all the shapes of the products and stocks are rectangular. This makes it highly suitable for applying heuristic algorithms, which produce fast results with high accuracy. In particular, the FFD (First Fit Decreasing) and BFD (Best Fit Decreasing) algorithms are especially effective.
	•	The FFD algorithm is well-suited for case studies that aim to minimize the number of stocks used.
	•	The BFD algorithm is ideal for cases where minimizing material waste is the priority.

**Implementation**
	FFD:
	•	FFD sorts the stocks and products in descending order of size.
	•	For each piece, it places it in the first available stock that has enough remaining space. If no existing stock can accommodate the piece, a new stock is used.
	•	Only one loop is used to handle both the cases before and after rotating the product.
	BFD:
	•	BFD also sorts the pieces in descending order of size.
	•	It iterates through all available stocks to find the one where placing the product results in the smallest remaining space.
	•	When trying to place a product into a stock, the code tests both the original and rotated versions of the product.
	•	To avoid repeatedly scanning all stocks for each function call, an additional variable "past" is used to store the index of the previously selected stock if the product can still fit.

**Results of Policy on the Test Data**
	•Seed 42 (GD Policy): Time elapsed: 0.0294 seconds
{'filled_ratio': 0.23, 'trim_loss': 0.45076284824748414}
	•Seed 42 (FFD Policy): Time elapsed: 0.0788 seconds
{'filled_ratio': 0.15, 'trim_loss': 0.4381501896109521}
	•Seed 42 (BFD Policy): Time elapsed: 3.0143 seconds
{'filled_ratio': 0.27, 'trim_loss': 0.30580856499083275}

**Conclusion**
For seed 42, both FFD and BFD provided significantly better results compared to the standard GD (Greedy) policy. FFD optimized the filled ratio, while BFD minimized trim loss. Both algorithms have been optimized by the team to run faster than typical FFD and BFD implementations.

However, neither FFD nor BFD guarantees the optimal solution for every test case. Therefore, in practical applications, FFD and BFD should be used in combination to support each other and achieve better results.

### CODE REVIEW

**Comment by martinakaduc** [comment]
Please read the submission instructions carefully. Otherwise I could not merge your PR (0 grade for code).

**Comment by BaoT08** [comment]
> Please read the submission instructions carefully. Otherwise I could not merge your PR (0 grade for code).

I have restored the s2210xxx folder and policy2210xxx.py. Could you help me check this again please?

**Comment by martinakaduc** [comment]
Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

**Comment by martinakaduc** [comment]
Last chance to revise the PR until the end of Dec 17.

**Pull request closed without merging**
