### PR TITLE
Submission of Group  2312517_2310886_2311614_2311548_2312365 

### PR DESCRIPTION
**Pull request by nguyen2966**
This folder include the Policy2312517_2310886_2311614_2311548_2312365.py,  this file consists of one policy called Policy2312517_2310886_2311614_2311548_2312365, it is a class with 2 seperated group of methods contribute to two different Policies, Genetic and Stock filled_rate optimize heuristic. Beside from the implementation file, I also included remodified cutting_stock.py file, where I edited step() function in order to bring my data sets into the environment. A brief pdf report on 2 policies and their performance on my datasets. File requirements.txt to include module that I used in my implementation file.

### CODE REVIEW

**Comment by martinakaduc** [comment]
Please read the submission instruction again

**Comment by nguyen2966** [comment]
> Please read the submission instruction again

I have reviewed the instruction and change submited folder's structure. Now it include implemented file (.py), requirement.txt file (where I inlucde my used module) and brief overview on two policies and their result in the README.md . Please give me feedback if my new submitsion is still invalid. Thank you .

**Comment by nguyen2966** [comment]
#### Policy Overview
This pull request introduces two algorithms, **Genetic Algorithm (GA)** and **Stock Filled Ratio Heuristic**, designed to optimize material waste reduction and computational efficiency for the 2D Irregular Cutting Stock Problem.

---

#### Workflow of the Algorithms

**Genetic Algorithm (GA)**:
- Utilizes evolutionary techniques such as crossover and mutation to optimize material placement.
- Scored solutions with a fitness function that balances maximizing filled ratio and minimizing trim loss.
- While powerful, it suffers from premature convergence and high computational costs.

**Stock Filled Ratio Heuristic**:
- Employs a deterministic approach to prioritize larger items and efficiently pack remaining space with smaller items.
- Focuses on minimizing trim loss while ensuring faster execution for small to medium datasets.

---

#### Implementation Details
- Source code for **Genetic Algorithm** is included in `{folder_submission}/src/genetic_algorithm.py`.
- Source code for **Stock Filled Ratio Heuristic** is included in `{folder_submission}/src/stock_filled_heuristic.py`.

---

#### Results
Based on the dataset of seed 42 used for testing, the following results were obtained in comparison with Greedy and Random policies(each policy run 1 time with the dataset):

| **Policy**               | **Filled Ratio** | **Trim Loss** | **Avg Runtime (s)** |
|---------------------------|------------------|---------------|----------------------|
| **Genetic Algorithm**     | 0.23            | 0.4141        | ~224.00             |
| **Stock Filled Heuristic**| 0.27            | 0.3036        | 45.19               |
| **Greedy**                | 0.23            | 0.4508        | 12.83               |
| **Random**                | 0.44            | 0.6861        | 10.93               |

---

#### Conclusion
The **Stock Filled Ratio Heuristic** demonstrates efficient and effective performance in reducing trim loss and improving material utilization, with reasonable computational cost. The **Genetic Algorithm**, while less efficient in runtime, provides insight into the potential of metaheuristic approaches but requires further refinement to overcome premature convergence and excessive runtime.

**Comment by nguyen2966** [comment]
> #### Policy Overview
> This pull request introduces two algorithms, **Genetic Algorithm (GA)** and **Stock Filled Ratio Heuristic**, designed to optimize material waste reduction and computational efficiency for the 2D Irregular Cutting Stock Problem.
> 
> #### Workflow of the Algorithms
> **Genetic Algorithm (GA)**:
> 
> * Utilizes evolutionary techniques such as crossover and mutation to optimize material placement.
> * Scored solutions with a fitness function that balances maximizing filled ratio and minimizing trim loss.
> * While powerful, it suffers from premature convergence and high computational costs.
> 
> **Stock Filled Ratio Heuristic**:
> 
> * Employs a deterministic approach to prioritize larger items and efficiently pack remaining space with smaller items.
> * Focuses on minimizing trim loss while ensuring faster execution for small to medium datasets.
> 
> #### Implementation Details
> * Source code for **Genetic Algorithm** is included in `{folder_submission}/src/genetic_algorithm.py`.
> * Source code for **Stock Filled Ratio Heuristic** is included in `{folder_submission}/src/stock_filled_heuristic.py`.
> 
> #### Results
> Based on the dataset of seed 42 used for testing, the following results were obtained in comparison with Greedy and Random policies(each policy run 1 time with the dataset):
> 
> **Policy**	**Filled Ratio**	**Trim Loss**	**Avg Runtime (s)**
> **Genetic Algorithm**	0.23	0.4141	~224.00
> **Stock Filled Heuristic**	0.27	0.3036	45.19
> **Greedy**	0.23	0.4508	12.83
> **Random**	0.44	0.6861	10.93
> #### Conclusion
> The **Stock Filled Ratio Heuristic** demonstrates efficient and effective performance in reducing trim loss and improving material utilization, with reasonable computational cost. The **Genetic Algorithm**, while less efficient in runtime, provides insight into the potential of metaheuristic approaches but requires further refinement to overcome premature convergence and excessive runtime.

**Pull request closed without merging**
