### PR TITLE
Submission (Group 79): 2252344_1952705_2352032_2352636_2352142

### PR DESCRIPTION
**Pull request by shiba-ho**
These are the two algorithms my group use to solve the CSP problem :

### 1. Greedy Algorithm (GreedyAlgorithm): 
- Greedy Algorithm makes a series of choices, each of which looks the best at the moment, aiming to find an overall optimal solution. In this case, the code continuously selects the first available stock and position that can accommodate the product without considering other potential placements that might be more optimal in the long run. It's a classic approach for problems where making locally optimal choices leads to a globally optimal solution.

>  Advantages: 
- Simple and Easy to implement.
- Find a feasible solution quickly.

> Disadvantages:
- May not find the optimal solution due to its immediate selection process.

### 2. Area-Based Sorting (BinPackingPolicysa):
- Items will be sorted in descending order based on their areas. Once the items are sorted, the algorithm attempts to place each item into the bins starting with the largest items. It will check both the original orientation and the rotated orientation (if applicable) to see if the item fits. Then, it will find the first valid position in each bin where the item can be placed without overlapping other items.

> Advantages:
- More structured approach.
- Better space utilization by placing larger items first.

> Disadvantages:
- More complex due to sorting and filtering.
- May not always find the optimal solution.

Mean filled ratio: 0.194  || Median filled ratio: 0.18.
Mean trim loss: 0.2703   || Median trim loss: 0.2351.

> Area-based Sorting Algorithm:
Mean filled ratio: 0.172  || Median filled ratio: 0.17.
Mean trim loss: 0.1848   || Median trim loss: 0.1958.

### CODE REVIEW

**Comment by martinakaduc** [comment]
Please read the submission instructions carefully. Otherwise I could not merge your PR (0 grade for code).

**Comment by shiba-ho** [comment]
> Please read the submission instructions carefully. Otherwise I could not merge your PR (0 grade for code).

Thank you for your comment.
I have updated the name of file and class of our code.
I hope it is correct to your comment.
I hope to you can check our code again at your convenience.
Thank you so much.

**Comment by martinakaduc** [comment]
Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

**Comment by shiba-ho** [comment]
> Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

I have revised and made some changes to our code. I hope it will be a mergeable pull request at the moment.
Thank you for your patience.
I hope you can check it at your convenience.
Thank you so much

**Pull request merged**
