### PR TITLE
Resubmission_group_10_2352383_2352439_2310846_2352381_2353175

### PR DESCRIPTION
**Pull request by Hoahoc11**
Team 10's submission represents two algorithms to solve the 2D Cutting Stock problem: Floor-Ceiling (FC) and Column Generation (CG). These algorithms aim to optimize space utilization, minimize trim loss, and improve runtime performance compared to traditional methods.

## **Team Members**
|No. | Full Name  | Student ID | Contribution|
|-------------| ------------- | ------------- | ---------------|
|1| Lê Gia Huy | 2352383 | Theory & Case Study |
|2| Nguyễn Tấn Hưng | 2352439 | Problem Formulation |
|3| Lê Minh Hào | 2310846 | Implementing Floor-Ceiling Algorithm |
|4| Huỳnh Nhật Huy | 2352381 |  Implementing Floor-Ceiling Algorithm|
|5| Đoàn Vĩ Tiến | 2353175 | Implementing Column Generation Algorithm |

## **Brief Description**
**Floor-Ceiling Algorithm (FC)**
The Floor-Ceiling Algorithm is a heuristic approach for solving two-dimensional cutting stock problems by packing items into rows (shelves) within a strip. Items are placed either on the "floor" (bottom-up) or the "ceiling" (top-down) based on space optimization, with larger items prioritized to maximize efficiency. Once shelves are created, they are packed into finite bins using the Best-Fit Decreasing Height (BFDH) strategy. This algorithm is effective for medium-sized problems, as it balances computational cost and space utilization. However, its O(n³) time complexity makes it less suitable for very large datasets.

**Column Generation Algorithm (CG)**
The Column Generation Algorithm is an optimization method that divides the problem into a Master Problem (MP) and a Subproblem. The MP combines existing cutting patterns to meet demand while minimizing material usage, while the Subproblem searches for new patterns with better efficiency. This iterative process alternates between refining patterns and optimizing their use, making it ideal for large-scale problems with complex constraints. While the algorithm achieves excellent material efficiency, its slow convergence near optimal solutions and high computational cost limit its practicality for time-sensitive applications.

## **Algorithm Performance Metrics**

image

### CODE REVIEW

**Comment by martinakaduc** [comment]
Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

**Comment by Hoahoc11** [comment]
> Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

Dear Professor, we have corrected the PR, please try to merge again and notify us if there's any further problem.

**Comment by martinakaduc** [comment]
Last chance to revise the PR until the end of Dec 17.

**Comment by iatucdel** [comment]
Merge lại đi ông

**Comment by iatucdel** [comment]
File changed còn đỏ dễ đi lắm

**Comment by Hoahoc11** [comment]
> File changed còn đỏ dễ đi lắm

merge thế nào vậy ô, tui không rành

**Comment by iatucdel** [comment]
clone lại bài của thầy -> xóa hết folder trong student_submission -> add folder của ông vào student submission -> commit -> lên đây merge lại

**Pull request closed without merging**
