### PR TITLE
Group 41 Submission: 2352420_2352533_2350030_2352157_2352179

### PR DESCRIPTION
**Pull request by cornel05**
1. **Brief Description**

- **Genetic Algorithms (GA):** A metaheuristic inspired by natural selection, used for optimization problems like the 2D Cutting Stock Problem. GA works by creating a population of cutting patterns, evaluating their efficiency based on material utilization, and improving solutions through selection, crossover, and mutation. Over generations, it finds patterns that minimize waste and maximize efficiency.
- **Skyline Heuristics:** A heuristic that maintains a "skyline" representing the highest points of placed items on the stock material. It places new items at the best position along the skyline, aiming to minimize gaps and optimize space usage. This method is efficient for arranging items while reducing waste in 2D cutting problems.

2. **Policy Implementation**

- 2352420: Modelling the problem, researching the theory of Genetic Algorithms (GA), writing report.
- 2352533: Modelling the problem, researching the theory of Skyline Heuristics, writing report.
- 2350030: Implementing GA, supporting Skyline Heuristics implementation, optimizing models.
- 2352157: Implementing Skyline Heuristics, supporting the GA implementation, optimizing models.
- 2352179: Researching case studies, supporting the GA implementation, optimizing models.

3. **Summarized Results**

|   Model   | Filled Ratio | Trim Loss |
|:---------:|:------------:|:---------:|
|  Genetic  |     0.22     |    0.1    |
|  Skyline  |     0.33     |   0.19    |
|   Greedy  |     0.44     |   0.13    |
|   Random  |     0.8      |   0.33    |

### CODE REVIEW

**Comment by martinakaduc** [comment]
Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

**Comment by cornel05** [comment]
I've pulled a new request already, please check it out. I'm sorry because I accidentally modified the open/close state of my group's old PR.

**Comment by cornel05** [comment]
Can you accept Group_41 (my group)'s new PR, because at the time you said to revise that PR (the old PR), I did not know which parts to revise, so I forked your repository again, but the changes are only the Directory name (sxxxxx/policyxxxxx.py), and nothing more. Can you please forgive me, and accepting my new PR, I cannot do anything more if my group's point is deduced by my accidental fault.

**Comment by cornel05** [comment]
Can you accept Group_41 (my group)'s new PR, because at the time you said to revise that PR (the old PR), I did not know which parts to revise, so I forked your repository again, but the changes are only the Directory name (sxxxxx/policyxxxxx.py), and nothing more. Can you please forgive me, and accepting my new PR, I cannot do anything more if my group's point is deduced by my accidental fault.

**Comment by cornel05** [comment]
I have revised the PR, but the deadline is already over. I hope you can forgive me and accept this overdue PR. I feel extremely sorry for my fault and your inconvenience.

**Pull request merged**
