### PR TITLE
Submission Group 54: 2352589-2353019-2353074-2350022-2353317

### PR DESCRIPTION
**Pull request by KhoaTr35**
# Cutting Stock Problem

##  Team member
| Name| ID|
|----------|-------------|
|Trần Anh Khoa|2352589|
|Trương Minh Quân|2353019|
|Hứa Gia Tân|2353074|
|Nguyễn Trần Minh Quang|2350022|
|Đinh Ngọc Việt|2353317|

## 1. Brief description of the Policies
**Genetic Algorithm**
- _Initialization:_ Generate an initial population of feasible solutions (chromosomes). Each chromosome represents a layout of items on stock sheets, ensuring items do not overlap and meet any rotation or placement constraints.

- _Evaluation:_ Calculate the fitness of each chromosome based on objectives like maximizing filled ratio or minimizing waste.
    
- _Selection:_ Choose parent chromosomes for reproduction using techniques like tournament selection, roulette wheel selection, or rank-based selection.
    
- _Crossover:_ Combine parts of two parent chromosomes to produce offspring that inherit characteristics of both parents while maintaining feasibility.
    
- _Mutation:_ Introduce random modifications to offspring, such as shifting, swapping, or rotating items, to explore diverse solutions.

- _Replacement:_ Form a new generation by replacing less-fit chromosomes with the offspring and repeat the process.

- _Termination:_ Stop after a fixed number of generations or when no significant improvement in fitness occurs. The best solution in the final population represents the outcome.

**FFD (First-Fit Decreasing)**
- Sorting: 
    + Arrange all items (demand pieces) in descending order of size. 
    + Sorting ensures that larger items are placed first, which helps to minimize wasted space and makes it easier to fit smaller items later.
- Placement Using First Fit:
    + For each item in the sorted list, place it into the first stock or bin that has enough remaining space.
    + If no bin has sufficient space, open a new bin and place the item there.
    + Repeat Until Completion.
    + Continue placing items into bins or opening new bins until all items are allocated.

## 2. Average results
| Policy | Filled Ratio | Trim Loss | Execution time(s) |
|--------|-------------|-----------|---------------|
| Genetic| 0.20        | 0.28    | 21.89         |
| FFD    | 0.23        | 0.36    | 16.38         |
| Greedy | 0.19        | 0.23   | 20.21          |

(The dataset is driven from random testing 100 episodes with similar seed in each episode for all Policies)

 The performance comparison of the Genetic Algorithm and the First Fit Decreasing algorithm is summarized as follows:
 • **Filled Ratio (FR)**: The Genetic algorithm achieves better stock utilization, particularly for larger product sets.
 • **Trimmed Loss (TL):** The Genetic Algorithm consistently minimizes leftover material, making it more efficient in reducing waste.
 • **Execution Time:** The FFD algorithm significantly outperforms the Genetic Algorithm in terms of computational efficiency and speed

## 3. Work distribution
| Work|        Incharge            |
|----------|-------------|
|Analyze Assignment|All members|
|Algorithm Research|Anh Khoa, Minh Quân, Minh Quang|
|Genetic Algo implement|Minh Quân|
|FFD Algo implement|Minh Quang|
|Evaluate model|Anh Khoa|
|Ilustration & graphs|Ngọc Việt|
|Report finalize|Ngọc Việt, Gia Tân|

### CODE REVIEW

**Comment by KhoaTr35** [comment]
# Cutting Stock Problem

## 1. Brief description of the Policies
**Genetic Algorithm**
- _Initialization:_ Generate an initial population of feasible solutions (chromosomes). Each chromosome represents a layout of items on stock sheets, ensuring items do not overlap and meet any rotation or placement constraints.

- _Evaluation:_ Calculate the fitness of each chromosome based on objectives like maximizing filled ratio or minimizing waste.
    
- _Selection:_ Choose parent chromosomes for reproduction using techniques like tournament selection, roulette wheel selection, or rank-based selection.
    
- _Crossover:_ Combine parts of two parent chromosomes to produce offspring that inherit characteristics of both parents while maintaining feasibility.
    
- _Mutation:_ Introduce random modifications to offspring, such as shifting, swapping, or rotating items, to explore diverse solutions.

- _Replacement:_ Form a new generation by replacing less-fit chromosomes with the offspring and repeat the process.

- _Termination:_ Stop after a fixed number of generations or when no significant improvement in fitness occurs. The best solution in the final population represents the outcome.

**FFD (First-Fit Decreasing)**
- Sorting: 
    + Arrange all items (demand pieces) in descending order of size. 
    + Sorting ensures that larger items are placed first, which helps to minimize wasted space and makes it easier to fit smaller items later.
- Placement Using First Fit:
    + For each item in the sorted list, place it into the first stock or bin that has enough remaining space.
    + If no bin has sufficient space, open a new bin and place the item there.
    + Repeat Until Completion.
    + Continue placing items into bins or opening new bins until all items are allocated.

## 2. Average results
| Policy | Filled Ratio | Trim Loss | Execution time(s) |
|--------|-------------|-----------|---------------|
| Genetic| 0.20        | 0.28    | 21.89         |
| FFD    | 0.23        | 0.36    | 16.38         |
| Greedy | 0.19        | 0.23   | 2.38          |

(The dataset is driven from random testing 100 episodes with similar seed in each episode for all Policies)

**Comment by martinakaduc** [comment]
Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

**Comment by KhoaTr35** [comment]
> Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

Dear professor i have adjust my pr, please check again. Thankyou for this incovenience

**Comment by KhoaTr35** [comment]
> Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

Dear Professor, i have revised my PR, please check again. Thankyou and sorry for the inconvenience

**Pull request merged**
