### PR TITLE
Submission 2033766_2033528

### PR DESCRIPTION
**Pull request by trandangtien1122**
**Team Members**

| Name                         | Student ID   | Contribution         |
|------------------------|--------------|----------------------|
| Trần Đăng Tiến          | 2033766     | implement QTable |
| Nguyễn Xuân Hoàng | 2033528    | Implement BestFit  |

**Brief Description**
There are two policies used to solve 2D cutting stock problem:

- **The BestFit algorithm:** is a heuristic approach commonly used in optimization problems like the cutting stock problem. It works by placing each item into the bin that will leave the least remaining space after the item is added, without exceeding the bin's capacity. This method aims to minimize unused space and maximize resource utilization.
- **A QTable** is a structured representation, often in the form of a 2D table, used to organize and track decisions or resource allocation in the cutting stock problem. It typically maps stock dimensions to required pieces, helping to optimize the cutting process.

**Summarized Results:**
| Criteria                                       | Q-Table  | BestFit    |
|-----------------------------------|-----------|-----------|
| Average Number of products   | 132         | 132         |
| Average running time [s]          | 43.162    | 93.098     |
| Average Success Rate               | 1.0          | 1.0           |
| Average Wasted Ratio              | 0.289      | 0.356       |
| Average Stocks Used                | 19.20      | 20.700     |

### CODE REVIEW

**Comment by martinakaduc** [comment]
Please read the submission instructions carefully. Otherwise I could not merge your PR (0 grade for code).

**Comment by trandangtien1122** [comment]
> Please read the submission instructions carefully. Otherwise I could not merge your PR (0 grade for code).

Hi Teacher, I updated the Title of PR and changed the name of policy to `Policy2210xxx`. Is the current PR correct?
Thank you!

**Comment by martinakaduc** [comment]
Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

**Comment by martinakaduc** [comment]
Closed PR as it does not comply with the submission guidelines.

**Pull request closed without merging**
