### PR TITLE
Submission from Group 91: 2252909 2252240 2252656 2352605

### PR DESCRIPTION
**Pull request by MrPartis**
Including 3 algorithms: Dynamic Programming, BruteForce, First Fit Decreasing algorithms
**Contributor lists:**
| Student name | Student ID | Contribution sections |
|--------|--------|--------|
| Lê Vũ Công Vinh | 2252909 | Modelling |
| Trần Cẩm Hoà | 2252240 | Coding Introduction + Acknowledge |
| Mai Nam Phương | 2252656 | Coding |
| Đỗ Tuấn Khôi | 2352605 | Algorithms + Latex | 

**About Algorithms**

1. First Fit Decreasing (FFD)
- An algorithm which firstly sorts items in decreasing size, then each will be place in the first sufficient stock with remaining spaces before inserting.
- Good to reduce waste or storage optimization.
2. Brute Force
- A manual method where it checks all feasible solutions to pick the most optimal one, according to fill ratio.
- However, the larger the input is, the more time it spends.
3. Dynamic Programming
- Attempt to break into smaller subproblems and solve them once, then store results for future references.
- May efficient if there are overlapping cases and optimal structures properties.

Result:
| Algorithm | Fill Ratio | Trim loss |
|--------|--------|--------|
| FFD | 0.23 | 0.229836 |
| Brute Force | 0.15 | 0.496632 |
| Dynamic Programming | 0.22 | 0.482652 |

Our algorithm is not optimized at maximum, those base error can be trusted

### CODE REVIEW

**Comment by martinakaduc** [comment]
Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

**Comment by martinakaduc** [comment]
Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

**Comment by MrPartis** [comment]
Is there anything else required, teacher?

**Comment by MrPartis** [comment]
I have modified the PR in order to match the requirements. I hope you can
consider and accept my submission.

**Pull request merged**
