### PR TITLE
Group 82 resubmisstion : 2312517_2310886_2311614_2311548_2312365

### PR DESCRIPTION
**Pull request by nguyen2966**
#### Policy Overview
This pull request introduces two algorithms, **Genetic Algorithm (GA)** and **Stock Filled Ratio Heuristic**, designed to optimize material waste reduction and computational efficiency for the 2D Irregular Cutting Stock Problem.

---
####Team commitment:
1. Nguyen Dang Khoa_2311614 : implemented Stock filled_rate optimize heuristic
2. Nguyen Le Nguyen_2312365: implemented Genetic algorithm
3. Ho Minh Nhien_2312517: revised code
4. Trinh Vu Duc Hai_2310886: revised code
5. Le Quang Khai_2311548: revised code

#### Workflow of the Algorithms

**Genetic Algorithm (GA)**:
- Utilizes evolutionary techniques such as crossover and mutation to optimize material placement.
- Scored solutions with a fitness function that balances maximizing filled ratio and minimizing trim loss.
- While powerful, it suffers from premature convergence and high computational costs.

**Stock Filled Ratio Heuristic**:
- Employs a deterministic approach to prioritize larger items and efficiently pack remaining space with smaller items.
- Focuses on minimizing trim loss while ensuring faster execution for small to medium datasets.

---

#### Results
Based on the dataset of seed 42 used for testing, the following results were obtained in comparison with Greedy and Random policies:

| **Policy**               | **Filled Ratio** | **Trim Loss** | **Runtime (s)** |
|---------------------------|------------------|---------------|----------------------|
| **Genetic Algorithm**     | 0.23            | 0.4141        | ~224.00             |
| **Stock Filled Heuristic**| 0.27            | 0.3036        | 45.19               |

---

#### Conclusion
The **Stock Filled Ratio Heuristic** demonstrates efficient and effective performance in reducing trim loss and improving material utilization, with reasonable computational cost. The **Genetic Algorithm**, while less efficient in runtime, provides insight into the potential of metaheuristic approaches but requires further refinement to overcome premature convergence and excessive runtime.

Kindly review and provide feedback!

### CODE REVIEW

**Comment by martinakaduc** [comment]
Please revise this PR and do not open the new one

**Comment by nguyen2966** [comment]
Teacher please tell my my mistake. I have carrfully read your instruction.
I created folder with our student ID and our implemented .py file also has
that name. Please help me.

Vào 19:32, T.2, 16 Th12, 2024 Duc Quang Nguyen ***@***.***>
đã viết:

**Comment by martinakaduc** [comment]
Please do not open new PR. Please edit your submitted PR.

**Comment by nguyen2966** [comment]
> Please do not open new PR. Please edit your submitted PR.

Please tell me which part to edit. I have reviewed the instruction carefully.

**Comment by nguyen2966** [comment]
> Please do not open new PR. Please edit your submitted PR.

I make sure that I revise the current PR, not the new one.

**Comment by nguyen2966** [comment]
> Please do not open new PR. Please edit your submitted PR.

I see the problem. Beside from this PR, I have many previous old PR. I gurantee that I have fully revise this PR. Please skip my old PR. I'm so sorry for this confussion. Please forgive me and merge this PR.

**Comment by nguyen2966** [comment]
Hiện tại thầy đã clode PR của nhóm em rồi ạ. Em đã chỉnh sửa vào PR đó,
mong thầy xem xét bỏ qua cho em ạ. Em không tạo PR mới mà đã edit PR đó ạ.

Vào 20:29, T.2, 16 Th12, 2024 Nguyên Lê ***@***.***> đã
viết:

**Pull request closed without merging**
