### PR TITLE
SUBMISSION_GROUP86_2353017_2353215__2352030_2352588

### PR DESCRIPTION
**Pull request by Quan-Quasar-Trinh**
Project Overview
This project tackles the 2D Cutting Stock Problem (CSP), aiming to minimize waste while efficiently utilizing stock sheets. The implemented solution explores three algorithms:

- Bottom-Left Decreasing (BLD): A placement algorithm that prioritizes fitting items into the bottom-left corner, using a decreasing size order.
- Next-Fit Decreasing Height (NFDH): A level-based heuristic packing strategy that moves to a new level once the current level is filled.
- First-Fit Decreasing Height (FFDH): A flexible level-based packing method that attempts to place items in the first level where they fit.

Policies Description
1. Bottom-Left Decreasing (BLD) Algorithm -Objective: Optimize material placement by leveraging a bottom-left-first placement heuristic. Approach:
+ Items are sorted by size (height or width) in descending order.
+ The algorithm attempts to place each item at the lowest y-coordinate and then the lowest x-coordinate where it fits.
+ Supports rotation of items for better utilization. -Strengths:
+Excellent for minimizing vertical space and achieving high packing density. -Challenges:
+Computationally intensive for larger datasets due to iterative placement checks.
2. Next-Fit Decreasing Height (NFDH) Algorithm
- Objective: Pack items into levels, reducing trim loss while maintaining simplicity.
- Approach:
+ Items are sorted by height in descending order.
+ Each level accommodates items until the current level’s width is exceeded, at which point a new level is started.
- Strengths:
+ Easy to implement and efficient for datasets where items have uniform dimensions. -Challenges:
+ May leave gaps within levels, resulting in wasted space for irregular-sized items.
3. First-Fit Decreasing Height (FFDH) Algorithm -Objective: Minimize waste by utilizing the first available level where an item fits. -Approach:
+Items are sorted by height in descending order.
+Each item is placed in the first level that has enough horizontal space. -Strengths:
+ Dynamic and better at minimizing gaps compared to NFDH.
- Challenges:
+ Slightly more complex due to the need for level management. Results Summary
Trim Loss:
-BLD: Consistently achieved the lowest trim loss among all three algorithms, especially for irregular item sizes. -NFDH: Moderate trim loss, particularly for datasets with varying item widths. -FFDH: Outperformed NFDH by better utilizing space but slightly behind BLD in overall efficiency. Performance:

-BLD: Computationally intensive for large datasets but provided the highest packing efficiency.
-NFDH: Fast and reliable for datasets with uniform or slightly irregular items.
-FFDH: Balanced performance, achieving better space utilization than NFDH at a slightly higher computational cost.

### CODE REVIEW

**Comment by martinakaduc** [comment]
Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

**Comment by Quan-Quasar-Trinh** [comment]
I apologized for not checking my email in time to revise our team's PR(#445 )so I have revised and resubmitted.

**Comment by Quan-Quasar-Trinh** [comment]
> Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

I apologized for not checking my email in time to revise our team's PR(https://github.com/martinakaduc/MM241-Assignment/pull/445 )so I have revised and resubmitted.

**Comment by Quan-Quasar-Trinh** [comment]
I have revised and resubmitted as PR(https://github.com/martinakaduc/MM241-Assignment/pull/456). If the PR does not comply with the submission guidelines. Please let us know.

**Comment by Quan-Quasar-Trinh** [comment]
> Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

I have revised and resubmitted as PR(#456 ). If the PR does not comply with the submission guidelines. Please let us know.

**Comment by martinakaduc** [comment]
Close PR as it does not comply with submission instructions.

**Pull request closed without merging**
