### PR TITLE
Submission Group 51: 2352429_2352430_2352444_2352428_2352355

### PR DESCRIPTION
**Pull request by Hungluthuan**
**A brief description:**
	The first policy implements a **Skyline-based heuristic approach** for solving the 2D cutting stock problem, aiming to maximize material usage while minimizing waste. It features are discussed in the following section.
	The second policy implements a **Genetic Algorithm approach**, which optimizes material usage by evolving solutions over generations by encoding cutting patterns as chromosomes and evaluates fitness based on waste minimization.
**1.	Skyline Algorithm**
Each stock is represented as a set of skyline segments. These segments track available space within the stock, dynamically updated as products are placed.
**2.	Genetic Algorithm**
Genetic algorithm is inspired by biological evolution: a chromosome represents a potential solution to the problem, encoded as an array of patterns. The algorithm evolves solutions by applying crossover to produce offspring, and mutation to introduce diversity. Chromosomes are evaluated in each generation based on a fitness function, and chosen as parents through the process of selection, ensuring that stronger traits are propagated to the next generation.
**The implementation of our policy:
Team Members:**
•	Lư Thuận Hưng (ID: 2352429,Leader)
•	Thượng Đình Hưng (ID: 2352444)
•	Lưu Đại Hưng (ID: 2352430)
•	Lê Mạnh Hưng (ID: 2352428)
•	Nguyễn Văn Hoàng (ID: 2352355)

Lư Thuận Hưng: Lead Developer for the genetic approach to the cutting-stock problem. Documented the outcomes of test cases, analyzed performance data, and recommended final improvements. Additionally, contributed to the research of theoretical concepts related to the 2D cutting-stock problem. Assisted in preparing the final report.
• Thượng Đình Hưng: Prepared the final report, summarized the theoretical research, implementation, testing, and results. Ensured proper documentation of the policy's workflow and effectiveness. Writing the weekly diary.
•  Lưu Đại Hưng: Assisted in the development of the Genetic approach to the cutting-stock problem.
•  Lê Mạnh Hưng: Researched the overall background information and objective of the project as part of the introduction, conducted research on the theoretical basis for the cutting-stock problem and skyline algorithm, summarized the project's key findings and insights in the conclusion.
• Nguyễn Văn Hoàng: Developed Skyline approach to cutting-stock problem. Assisted with the research of theoretical concepts related to the skyline and genetic algorithm.
**The summarized results:**
	In this pull request, we evaluate the effect of the **Skyline Policy**  and **Genetic Policy** by comparing it with two default algorithm that have been given, which are **Greedy Policy** and **Random Policy**. The statistics is based on three aspects: **excution time, filled ratio** and **trim loss**:

Policy | Execution   time (s) | Filled ratio   (%) | Trim loss (%)
-- | -- | -- | --
Greedy | 56.89 | 0.21 | 0.24
Random | 27.59 | 0.72 | 0.78
Skyline | 33.97 | 0.14 | 0.24
Genetic | 41.51 | 0.19 | 0.36

**Summary:** 
•	**Greedy Policy** has the median filled ratio of 0.21, with the longest execution time of 56.89.
•	**Random Policy** has achieved the shortest running time of 27.59, although it has the worst filled ratio with 0.72.
•	**Skyline Policy** just run a little bit slower than Random Policy but the result is incredible with a drop in filled ratio is 0.14.
•	**Genetic Policy** has very long execution time of 41.51, but achieving the second-lowest filled ratio of 0.19.
•	**Additional Information:**
		The Greedy algorithm requires long execution time due to its need to iterate through all available positions in the stock, while selecting only the first suitable one. This approach places products based solely on immediate available space, without accounting for potential future placements.
	In contrast, the Random algorithm achieves the fastest execution time but is highly unstable. This is because it selects a stock location randomly, provided it can accommodate the product, without considering the current arrangement of placements. Both Greedy and Random algorithm disregard the impact of current decisions on future placements, which affects long-term optimization.
	Skyline performs better than Random and Greedy algorithms due to its structured approach to space optimization. Skyline dynamically builds an optimal layout by maintaining a dynamic skyline of available space. This method minimizes local waste and maximizes space utilization by evaluating multiple placement options for each product. Skyline’s heuristic-driven strategy results is a more efficient and space-aware packing solution, leading to better overall performance in terms of both waste reduction and stock utilization.
	The Genetic algorithm requires long execution time due to its iterative nature, involving processes like selection, crossover, and mutation over multiple generations. Theoretically, the Genetic algorithm should perform best at finding high-quality solutions because it explores a broader solution space. However, its filled ratio, while improved compared to Random and Greedy prolicy, is only slightly higher than that of the Skyline algorithm. This could be due to an unsuitable population size, crossover rate, or mutation rate, which can be further tuned for better optimization.

### CODE REVIEW

**Comment by martinakaduc** [comment]
Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

**Comment by Hungluthuan** [comment]
> Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.

Dear Professor, I apologize on behalf of my group for the error in our previous submission (PR #163). We have since closed that pull request and opened a new one (PR #385), which can be found at the following link: https://github.com/martinakaduc/MM241-Assignment/pull/385. I kindly ask if you could review it to ensure it meets the assignment requirements.

**Comment by Hungluthuan** [comment]
> Please revise the PR in Dec 16. Otherwise, your group will get 0 score for code.
@martinakaduc  I have accidently deleted the old repository and forked it again, so I am unable to reopen our old PR. I sincerely apologize for my mistake and hope that you can accept our new PR. Please let me know if there is another solution for this case

**Comment by Hungluthuan** [comment]
Dear Professor, I'm the group leader of group 51. I have accidently deleted
the old repository and forked it again, so I am unable to reopen our old
PR. I sincerely apologize for my mistake and hope that you can accept our
new PR. Please let me know if there is another solution for this case. I
apologize on behalf of my group for the error in our previous submission
(PR #163). We have since closed that pull request and opened a new one (PR
#385), which can be found at the following link:

https://github.com/martinakaduc/MM241-Assignment/pull/385

. I kindly ask if you could review it to ensure it meets the assignment
requirements.




Vào Th 2, 16 thg 12, 2024 vào lúc 18:46 Duc Quang Nguyen <
***@***.***> đã viết:

**Pull request closed without merging**
